# -*- coding: utf-8 -*-
"""중간고사 전 함수정리 4-5강.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZcDTFvsbpGOB6aODglm8Y_QGNvoroLTJ

##그리기 함수
"""

line을 그리는 함수는
cv2.line(그려지는 이미지, 시작점, 끝점, 색, 굵기, 라인타입은 생략 가능)

사각형 그리는 함수
cv2.rectangle(그려지는 이미지 좌상점 우하점 색 굵기 라인타입)
cv2.rectangle(그려지는 이미지 (좌상 우하 점) 색 굵기 라인타입)

이때 굵기가 -1이면 모양의 경우는 색이 채워진다.

문자열
cv2.putText(이미지, text, (좌하 점 =시작점), 폰트종류, 폰트 크기, 색, 굵기, 라인타입)
여러개를 엮어서 새로운 폰트를 만들고 싶으면 cv2 폰트와 다른 cv2 폰트를 | 연산하면 된다다

원그리기
cv2.circle(이미지, center, 반지름, 색, 굵기, 라인 타입)
여기도 굵기가 -1이면 도형 채우기가 된다.

타원그리기

cv2.ellipse(이미지 (x y중심), (x,y각각의 반지름), 각도 , 시작 각도(3시 방향이 0도 시계 방향), 끝 각도, 색,굵기, 라인타입, )
이걸로 반원을 그릴 수 있음!!!


겹쳐지는 선 그리기
참거짓 결과, 시작점, 끝점=cv2.clipline(imgae, 시작점(x,y), 끝점(x,y))


화살표 그리기
cv2.arrowedLine(이미지 시작점 끝점 색 두께, 라인타입,shift =0, 라인 두께(실수))
cv2.arrowedLIne(image, (10,100),(50,100), red, 3, cv2.LINE_AA, 0, 0.5)

"""##다각형 그리기!!! 꼭 실습해보기!! 유일하게 안해본거

## 중요!! 점들을 만들땐 꼭!!!! np.int32로!!
"""

cv2.polylines(이미지, 점들, isClosed, 색, 두께, 라인 타입, shift)
점들은 어레이로 만든다음
wn
pt= np.array([
              [200,20],
              [250,30],
              [300,20]
              ], np.int32)

pts = 입력받은 점들.reshape((-1,1,2))

cv2.polylines(img, pts, isClosed =True, red, thickness, cv2.LINE_AA,0)
이런식으로!!
근데 -1로 하면 오류남 색채울때

개폐에서 False라 하면 마지막점과 첫점을 이어주지 않음!!

"""##영상파일 읽고 쓰는 방법"""

cv2.imread(이미지 주소,mode)
mode = cv2.IMREAD_GRAYSCALE
      cv2.IMREAD_COLOR
      cv2.IMREAD_ANYDEPTH -> 입력 파일에 정의된 깊이에 따라 16/32비트로 변환, 설정이 없으면 8

"""## np로 사용(numpy)로 사용할 있는 방법


"""

np.random.randint(10,size=5)
는 0~9까지 중 5개 랜덤 숫자를 뽑아내기
범위 지정은
np.random.randint(10,20,size(2,6))
도 가능
이건 10이상 20미만 숫자를 (2*6)의 list 형태로 표현하는것이다.

빈 이미지 만들기

color :
image = np.zeros((height,width,3), np.uint8)
gray :
image = np.zeros((height,width,), np.uint8)